### PR TITLE
Correct error message in _beforeStep

### PR DESCRIPTION
**Pull request by iredchuk**
* Also allow empty string for selector

### CODE REVIEW

**Comment by hubidu** [comment]
Sorry, I don't understand. How and why should an empty string locator be highlighted?

I'll do something else to make the message go away.

**Comment by iredchuk** [comment]
OK, if a previous function is only for highlighting, then you are right, we should not do it. But I would still not log the message for empty strings since we intentionally use them, and also correct the log message.

**Comment by hubidu** [comment]
Just published 0.6.18. Message should no longer appear. 

NOTE: npm usually takes some time until version is available.

**Comment by iredchuk** [comment]
Thanks

**Pull request closed without merging**
